// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: Armageddon1

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Name1;
extern lv_obj_t * ui_Encoder1;
extern lv_obj_t * ui_PosDeg1;
extern lv_obj_t * ui_Target1;
extern lv_obj_t * ui_TargetDeg1;
extern lv_obj_t * ui_PPM1;
extern lv_obj_t * ui_PPMOUT1;
extern lv_obj_t * ui_Name2;
extern lv_obj_t * ui_Encoder2;
extern lv_obj_t * ui_PosDeg2;
extern lv_obj_t * ui_Target2;
extern lv_obj_t * ui_TargetDeg2;
extern lv_obj_t * ui_PPM2;
extern lv_obj_t * ui_PPMOUT2;
extern lv_obj_t * ui_Name3;
extern lv_obj_t * ui_Encoder3;
extern lv_obj_t * ui_PosDeg3;
extern lv_obj_t * ui_Target3;
extern lv_obj_t * ui_TargetDeg3;
extern lv_obj_t * ui_PPM3;
extern lv_obj_t * ui_PPMOUT3;
extern lv_obj_t * ui_Name4;
extern lv_obj_t * ui_Encoder4;
extern lv_obj_t * ui_PosDeg4;
extern lv_obj_t * ui_Target4;
extern lv_obj_t * ui_TargetDeg4;
extern lv_obj_t * ui_PPM4;
extern lv_obj_t * ui_PPMOUT4;
extern lv_obj_t * ui_Name5;
extern lv_obj_t * ui_Encoder5;
extern lv_obj_t * ui_PosDeg5;
extern lv_obj_t * ui_Target5;
extern lv_obj_t * ui_TargetDeg5;
extern lv_obj_t * ui_PPM5;
extern lv_obj_t * ui_PPMOUT5;
extern lv_obj_t * ui_Name6;
extern lv_obj_t * ui_Encoder6;
extern lv_obj_t * ui_PosDeg6;
extern lv_obj_t * ui_Target6;
extern lv_obj_t * ui_TargetDeg6;
extern lv_obj_t * ui_PPM6;
extern lv_obj_t * ui_PPMOUT6;
extern lv_obj_t * ui_Name7;
extern lv_obj_t * ui_Encoder7;
extern lv_obj_t * ui_PosDeg7;
extern lv_obj_t * ui_Target7;
extern lv_obj_t * ui_TargetDeg7;
extern lv_obj_t * ui_PPM7;
extern lv_obj_t * ui_PPMOUT7;
extern lv_obj_t * ui_Name8;
extern lv_obj_t * ui_Encoder8;
extern lv_obj_t * ui_PosDeg8;
extern lv_obj_t * ui_Target8;
extern lv_obj_t * ui_TargetDeg8;
extern lv_obj_t * ui_PPM8;
extern lv_obj_t * ui_PPMOUT8;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

