// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: Armageddon1

#include "ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_Name1 = NULL;
lv_obj_t * ui_Encoder1 = NULL;
lv_obj_t * ui_PosDeg1 = NULL;
lv_obj_t * ui_Target1 = NULL;
lv_obj_t * ui_TargetDeg1 = NULL;
lv_obj_t * ui_PPM1 = NULL;
lv_obj_t * ui_PPMOUT1 = NULL;
lv_obj_t * ui_Name2 = NULL;
lv_obj_t * ui_Encoder2 = NULL;
lv_obj_t * ui_PosDeg2 = NULL;
lv_obj_t * ui_Target2 = NULL;
lv_obj_t * ui_TargetDeg2 = NULL;
lv_obj_t * ui_PPM2 = NULL;
lv_obj_t * ui_PPMOUT2 = NULL;
lv_obj_t * ui_Name3 = NULL;
lv_obj_t * ui_Encoder3 = NULL;
lv_obj_t * ui_PosDeg3 = NULL;
lv_obj_t * ui_Target3 = NULL;
lv_obj_t * ui_TargetDeg3 = NULL;
lv_obj_t * ui_PPM3 = NULL;
lv_obj_t * ui_PPMOUT3 = NULL;
lv_obj_t * ui_Name4 = NULL;
lv_obj_t * ui_Encoder4 = NULL;
lv_obj_t * ui_PosDeg4 = NULL;
lv_obj_t * ui_Target4 = NULL;
lv_obj_t * ui_TargetDeg4 = NULL;
lv_obj_t * ui_PPM4 = NULL;
lv_obj_t * ui_PPMOUT4 = NULL;
// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Name1 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Name1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Name1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Name1, -306);
    lv_obj_set_y(ui_Name1, -216);
    lv_obj_set_align(ui_Name1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Name1, "Left Shoulder");
    lv_obj_set_style_text_font(ui_Name1, &ui_font_RoboticLegends24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Name1, &ui_font_RoboticLegends24, LV_PART_MAIN | LV_STATE_USER_1);

    ui_Encoder1 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Encoder1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Encoder1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Encoder1, -301);
    lv_obj_set_y(ui_Encoder1, -187);
    lv_obj_set_align(ui_Encoder1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Encoder1, "Encoder Angle");
    lv_obj_set_style_text_font(ui_Encoder1, &ui_font_RoboticLegends24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PosDeg1 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_PosDeg1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PosDeg1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PosDeg1, -299);
    lv_obj_set_y(ui_PosDeg1, -160);
    lv_obj_set_align(ui_PosDeg1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PosDeg1, "0.00");
    lv_obj_set_style_text_font(ui_PosDeg1, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Target1 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Target1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Target1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Target1, -313);
    lv_obj_set_y(ui_Target1, -127);
    lv_obj_set_align(ui_Target1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Target1, "Target Angle");
    lv_obj_set_style_text_font(ui_Target1, &ui_font_RoboticLegends24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TargetDeg1 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_TargetDeg1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TargetDeg1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TargetDeg1, -299);
    lv_obj_set_y(ui_TargetDeg1, -99);
    lv_obj_set_align(ui_TargetDeg1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TargetDeg1, "0.00");
    lv_obj_set_style_text_font(ui_TargetDeg1, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PPM1 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_PPM1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PPM1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PPM1, -311);
    lv_obj_set_y(ui_PPM1, -72);
    lv_obj_set_align(ui_PPM1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PPM1, "PPM Output");
    lv_obj_set_style_text_font(ui_PPM1, &ui_font_RoboticLegends24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PPMOUT1 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_PPMOUT1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PPMOUT1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PPMOUT1, -306);
    lv_obj_set_y(ui_PPMOUT1, -45);
    lv_obj_set_align(ui_PPMOUT1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PPMOUT1, "0000");
    lv_obj_set_style_text_font(ui_PPMOUT1, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Name2 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Name2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Name2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Name2, -300);
    lv_obj_set_y(ui_Name2, -8);
    lv_obj_set_align(ui_Name2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Name2, "Left Upper Arm");
    lv_obj_set_style_text_font(ui_Name2, &ui_font_RoboticLegends24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Name2, &ui_font_RoboticLegends24, LV_PART_MAIN | LV_STATE_USER_1);

    ui_Encoder2 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Encoder2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Encoder2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Encoder2, -300);
    lv_obj_set_y(ui_Encoder2, 22);
    lv_obj_set_align(ui_Encoder2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Encoder2, "Encoder Angle");
    lv_obj_set_style_text_font(ui_Encoder2, &ui_font_RoboticLegends24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PosDeg2 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_PosDeg2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PosDeg2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PosDeg2, -301);
    lv_obj_set_y(ui_PosDeg2, 50);
    lv_obj_set_align(ui_PosDeg2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PosDeg2, "0.00");
    lv_obj_set_style_text_font(ui_PosDeg2, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Target2 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Target2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Target2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Target2, -307);
    lv_obj_set_y(ui_Target2, 88);
    lv_obj_set_align(ui_Target2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Target2, "Target Angle");
    lv_obj_set_style_text_font(ui_Target2, &ui_font_RoboticLegends24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TargetDeg2 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_TargetDeg2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TargetDeg2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TargetDeg2, -300);
    lv_obj_set_y(ui_TargetDeg2, 119);
    lv_obj_set_align(ui_TargetDeg2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TargetDeg2, "0.00");
    lv_obj_set_style_text_font(ui_TargetDeg2, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PPM2 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_PPM2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PPM2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PPM2, -298);
    lv_obj_set_y(ui_PPM2, 154);
    lv_obj_set_align(ui_PPM2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PPM2, "PPM Output");
    lv_obj_set_style_text_font(ui_PPM2, &ui_font_RoboticLegends24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PPMOUT2 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_PPMOUT2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PPMOUT2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PPMOUT2, -301);
    lv_obj_set_y(ui_PPMOUT2, 188);
    lv_obj_set_align(ui_PPMOUT2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PPMOUT2, "0000");
    lv_obj_set_style_text_font(ui_PPMOUT2, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Name3 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Name3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Name3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Name3, -108);
    lv_obj_set_y(ui_Name3, -217);
    lv_obj_set_align(ui_Name3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Name3, "Left Elbow");
    lv_obj_set_style_text_font(ui_Name3, &ui_font_RoboticLegends24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Name3, &ui_font_RoboticLegends24, LV_PART_MAIN | LV_STATE_USER_1);

    ui_Encoder3 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Encoder3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Encoder3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Encoder3, -104);
    lv_obj_set_y(ui_Encoder3, -186);
    lv_obj_set_align(ui_Encoder3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Encoder3, "Encoder Angle");
    lv_obj_set_style_text_font(ui_Encoder3, &ui_font_RoboticLegends24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PosDeg3 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_PosDeg3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PosDeg3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PosDeg3, -99);
    lv_obj_set_y(ui_PosDeg3, -161);
    lv_obj_set_align(ui_PosDeg3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PosDeg3, "0.00");
    lv_obj_set_style_text_font(ui_PosDeg3, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Target3 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Target3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Target3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Target3, -121);
    lv_obj_set_y(ui_Target3, -125);
    lv_obj_set_align(ui_Target3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Target3, "Target Angle");
    lv_obj_set_style_text_font(ui_Target3, &ui_font_RoboticLegends24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TargetDeg3 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_TargetDeg3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TargetDeg3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TargetDeg3, -97);
    lv_obj_set_y(ui_TargetDeg3, -97);
    lv_obj_set_align(ui_TargetDeg3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TargetDeg3, "0.00");
    lv_obj_set_style_text_font(ui_TargetDeg3, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PPM3 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_PPM3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PPM3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PPM3, -111);
    lv_obj_set_y(ui_PPM3, -67);
    lv_obj_set_align(ui_PPM3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PPM3, "PPM Output");
    lv_obj_set_style_text_font(ui_PPM3, &ui_font_RoboticLegends24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PPMOUT3 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_PPMOUT3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PPMOUT3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PPMOUT3, -103);
    lv_obj_set_y(ui_PPMOUT3, -40);
    lv_obj_set_align(ui_PPMOUT3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PPMOUT3, "0000");
    lv_obj_set_style_text_font(ui_PPMOUT3, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Name4 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Name4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Name4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Name4, -105);
    lv_obj_set_y(ui_Name4, -8);
    lv_obj_set_align(ui_Name4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Name4, "Left Claw");
    lv_obj_set_style_text_font(ui_Name4, &ui_font_RoboticLegends24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Name4, &ui_font_RoboticLegends24, LV_PART_MAIN | LV_STATE_USER_1);

    ui_Encoder4 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Encoder4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Encoder4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Encoder4, -108);
    lv_obj_set_y(ui_Encoder4, 21);
    lv_obj_set_align(ui_Encoder4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Encoder4, "Encoder Angle");
    lv_obj_set_style_text_font(ui_Encoder4, &ui_font_RoboticLegends24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PosDeg4 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_PosDeg4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PosDeg4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PosDeg4, -95);
    lv_obj_set_y(ui_PosDeg4, 49);
    lv_obj_set_align(ui_PosDeg4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PosDeg4, "0.00");
    lv_obj_set_style_text_font(ui_PosDeg4, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Target4 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Target4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Target4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Target4, -114);
    lv_obj_set_y(ui_Target4, 85);
    lv_obj_set_align(ui_Target4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Target4, "Target Angle");
    lv_obj_set_style_text_font(ui_Target4, &ui_font_RoboticLegends24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TargetDeg4 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_TargetDeg4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TargetDeg4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TargetDeg4, -94);
    lv_obj_set_y(ui_TargetDeg4, 120);
    lv_obj_set_align(ui_TargetDeg4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TargetDeg4, "0.00");
    lv_obj_set_style_text_font(ui_TargetDeg4, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PPM4 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_PPM4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PPM4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PPM4, -97);
    lv_obj_set_y(ui_PPM4, 156);
    lv_obj_set_align(ui_PPM4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PPM4, "PPM Output");
    lv_obj_set_style_text_font(ui_PPM4, &ui_font_RoboticLegends24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PPMOUT4 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_PPMOUT4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PPMOUT4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PPMOUT4, -100);
    lv_obj_set_y(ui_PPMOUT4, 187);
    lv_obj_set_align(ui_PPMOUT4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PPMOUT4, "0000");
    lv_obj_set_style_text_font(ui_PPMOUT4, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_Name1 = NULL;
    ui_Encoder1 = NULL;
    ui_PosDeg1 = NULL;
    ui_Target1 = NULL;
    ui_TargetDeg1 = NULL;
    ui_PPM1 = NULL;
    ui_PPMOUT1 = NULL;
    ui_Name2 = NULL;
    ui_Encoder2 = NULL;
    ui_PosDeg2 = NULL;
    ui_Target2 = NULL;
    ui_TargetDeg2 = NULL;
    ui_PPM2 = NULL;
    ui_PPMOUT2 = NULL;
    ui_Name3 = NULL;
    ui_Encoder3 = NULL;
    ui_PosDeg3 = NULL;
    ui_Target3 = NULL;
    ui_TargetDeg3 = NULL;
    ui_PPM3 = NULL;
    ui_PPMOUT3 = NULL;
    ui_Name4 = NULL;
    ui_Encoder4 = NULL;
    ui_PosDeg4 = NULL;
    ui_Target4 = NULL;
    ui_TargetDeg4 = NULL;
    ui_PPM4 = NULL;
    ui_PPMOUT4 = NULL;

}
